title: Miracle Chukwu
logo: linkedin_profile.jpg
description: Data Analyst Portfolio 
#show_downloads: true
theme: jekyll-theme-minimal
body:  Work Experience

### Document Controller (Data Analyst)
**Asommat International Services Limited**  
_March 2022 – Present_  
_Port Harcourt (Remote)_

- **Reduced processing time by 10%** through automation using VBA scripting, streamlining data management processes.
- **Collected, cleaned, and preprocessed large datasets** from multiple sources to ensure data accuracy and integrity, enhancing the reliability of business insights.
- **Analyzed large data sets to identify patterns and trends**, providing actionable insights and visualizations to support decision-making.
- **Collaborated with the management team** to analyze results, establish business needs, and provide comprehensive reports, facilitating strategic planning.

### Business Data Analyst
**Viceroy Technologies**  
_September 2021 – October 2023_  
_Port Harcourt_

- **Increased data accuracy by 5%** through meticulous processing of data from multiple sources, ensuring high-quality inputs for analysis.
- **Identified cost-saving opportunities leading to an 8% reduction in project expenses** by conducting thorough exploratory data analysis.
- **Implemented process improvements that reduced project lead times by 10%**, resulting in enhanced operational efficiency and timely project delivery.
- **Developed detailed reports and dashboards** to communicate findings and support data-driven decision-making across the organization.

---


## Education

- Aspire Leadership Program | Aspire Institute, Jan 2024 – Apr 2024
- Bachelors of Engineering (Hons.) | Michael Okpara University of Agriculture Umudike, Abia State, Nigeria, Nov 2014 – May 2021, CGPA: 4.07/5.00
